### PR TITLE
need new vtn7_4

### PR DESCRIPTION
**Pull request by JamesMcBean**

### CODE REVIEW

**Comment by josephcslater** [comment]
vtn? What do you need a new one of?

**Comment by JamesMcBean** [comment]
Sorry about that I was trying to pull the latest version of the vibration
tool box. I ended up figuring out I was attempting to input a a column
vector and a row vector into vtb7_4 once I corrected that the code worked.

Thanks for following up

**Comment by josephcslater** [comment]
So: an easy way to make valuable contributions is to write code at the beginning that checks that the inputs have the right form (column versus row).

**Comment by josephcslater** [comment]
Is there anything here? I can reopen it.

**Pull request closed without merging**
